### ISSUE TITLE
numpy complex  has changed

### ISSUE THREAD

**Issue by rdejtiar** [susantoj/line-constants#1]
Running the script with python 3.8  and numpy 1.24.3  I´ve found :
np.complex has to change to complex128
on line  220
self_Z = np.complex128(R_int + Rp+( X_int + X_geo + Xp)*1j)

on line 256 
  self_Z = np.complex128(Rp+ (X_geo + Xp)*1j)

**Comment by susantoj** [comment]
Thanks for picking this up, should be fixed now!
